Importing required libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
# loading the data set to a variable using pandas dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [4]:
# head() method returns top 5 data points from the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
# tail() method retuens the last 5 data points from the data set
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [6]:
# info() method returns the information of the given dataset
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
# isnull() returns 0 if data is null else 1 for individual values
# by adding all such values we get the total no.of null values - we use sum() method
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
# As the data is fully available, we don't need to fill the values
# Distribution of ligit and fraudalant transaction
credit_card_data["Class"].value_counts()
# The below data is unbalanced because ,more than 90% of data is in one particular class
# 0 ------> 284315(Normal Transaction)
# 1 ------> 492(Fraudalant Transation)
# Hence the data is unbalanced

0    284315
1       492
Name: Class, dtype: int64

In [10]:
# Dividing the data for further analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [14]:
# Finding the shape of divided data
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [16]:
# Statistical measurements of the legit data
# like mean, min, max, std etc..
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [17]:
# Statistical measurements of the fraud data
# like mean, min, max, std etc..
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [20]:
# Compare the values for both transactions
# It groups the similar class and then find the mean of the grouped data set
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [21]:
# Under sampling
# Building a sample dataset from original dataset thaat contains similar distributions of legit and fraud transactions
# Number of a fraudalant Transactions - 492
# From the legit transaction take 429 random sample data by using sample() method
legit_sample = legit.sample(n = 429)

In [22]:
# Concating the two dataframes
# After getting the sample data concat the both fraud and legit sample dataset
new_data = pd.concat([legit_sample, fraud], axis = 0)
# if axis is 0, values by row
# if axis value is 1, value by column

In [23]:
# head() of the new dataset
new_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
242459,151499.0,-3.865926,2.714223,1.062585,-2.712831,2.878858,-0.282310,5.380055,-4.826682,7.435639,...,-2.058062,-0.033685,-0.618249,-0.382015,-0.165741,-0.391210,-1.241531,-2.605667,25.79,0
88564,62195.0,-1.302787,1.093884,2.340569,1.064613,0.706188,0.669410,0.434528,0.269922,-1.336151,...,0.256782,0.565064,-0.379080,-0.288033,0.389326,-0.031585,-0.240693,0.113381,15.21,0
84027,60131.0,1.141102,-0.410747,1.276300,0.264631,-1.421098,-0.648450,-0.648683,0.014727,1.070214,...,-0.080319,-0.102068,0.076771,0.788332,0.057411,0.967390,-0.038916,0.024346,35.95,0
106548,70006.0,-1.750726,1.187191,0.733108,-0.172249,0.278609,0.146313,0.224221,0.463502,-0.033465,...,-0.282991,-0.331406,0.256190,-0.356356,-0.313042,0.017222,-0.673486,-0.722859,1.98,0
131154,79511.0,-0.548437,1.261409,0.851854,0.963044,0.238254,0.279797,0.172739,0.537026,-0.761974,...,0.069259,0.125684,-0.145401,-0.791811,-0.246002,-0.267088,0.057277,0.077477,3.96,0

In [25]:
# counts the available values and dispaly them
new_data["Class"].value_counts()
# 0,1 --> 429

1    492
0    429
Name: Class, dtype: int64

In [27]:
# finds the mean and returns it
new_data.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96694.883450,0.032621,-0.076196,-0.038389,-0.044881,-0.118758,0.058903,0.032944,-0.086375,0.006481,...,0.021726,0.004545,0.028021,-0.009504,0.022391,-0.006073,-0.003905,0.004116,-0.022762,109.665524
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [29]:
# Splitting the data into Features and Targets
# Drop the Class value
# storing the Class value in other variable separatly
X = new_data.drop(columns = "Class", axis = 1)
Y = new_data["Class"]

In [30]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
242459  151499.0 -3.865926  2.714223  1.062585 -2.712831  2.878858 -0.282310
88564    62195.0 -1.302787  1.093884  2.340569  1.064613  0.706188  0.669410
84027    60131.0  1.141102 -0.410747  1.276300  0.264631 -1.421098 -0.648450
106548   70006.0 -1.750726  1.187191  0.733108 -0.172249  0.278609  0.146313
131154   79511.0 -0.548437  1.261409  0.851854  0.963044  0.238254  0.279797
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
242459  5.380055 -4.826682  7.435639  ...  4.145950 -2.058062 -0.033685
88564   0.434528  0.269922 -1.336151  ... -0.145477  0.256782  0.565064
84027  -0.648683  0.014727  1.070214  ... -0.020875 -0.080319 -0.102068
106548  0.224221  0.463502 -0.033465  ... -0.093440 -0.282991 -0.331406
131154  0.172739  0.537026 -0.761974  ... -0.108303  0.069259  0.125684
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
242459 -0.618249 -0.382015 -0.165741 -0.391210 -1.241531 -2.605667   25.79
88564  -0.379080 -0.288033  0.389326 -0.031585 -0.240693  0.113381   15.21
84027   0.076771  0.788332  0.057411  0.967390 -0.038916  0.024346   35.95
106548  0.256190 -0.356356 -0.313042  0.017222 -0.673486 -0.722859    1.98
131154 -0.145401 -0.791811 -0.246002 -0.267088  0.057277  0.077477    3.96
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[921 rows x 30 columns]

In [31]:
print(Y)

242459    0
88564     0
84027     0
106548    0
131154    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 921, dtype: int64

Splitting the data into training data and testing data

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)
# 20% of the data is used for test data
# 80% of the data is used for train data

In [35]:
# shape of X,X_test and X_trian
print(X.shape, X_train.shape, X_test.shape)

(921, 30) (736, 30) (185, 30)

Model Training using Logidtic Regression

In [37]:
model = LogisticRegression()

In [39]:
# training the Logistic Regression model eith training data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

In [44]:
# Model evaluation using Accuracy Score
# Compares the predicted values from X_train_prediction and actual values from Y_train
X_train_prediction = model.predict(X_train)
training_accuracy = accuracy_score(X_train_prediction, Y_train)

In [49]:
print("Accuracy on the training data : ", training_accuracy)

Accuracy on the training data :  0.9415760869565217

In [50]:
# Evaluating the model by using unseen data is test data
X_test_prediction = model.predict(X_test)
testing_accuracy = accuracy_score(X_test_prediction, Y_test)

In [51]:
print("Accuacy on the testing data : ", testing_accuracy)

Accuacy on the testing data :  0.9135135135135135